"use client";
import{useEffect,useState}from"react";import{useRouter}from"next/navigation";import PortalNav from"../components/PortalNav";import{api,getToken}from"../lib/api";import"../portal.css";
type Course={id:number;name:string;description:string;difficulty:string;duration_minutes:number;total_levels:number;credits_required:number;category:string;certificate_company:string;enrolled:number;can_unlock:number};
export default function Courses(){const router=useRouter();const[courses,setCourses]=useState<Course[]>([]);const[balance,setBalance]=useState(0);const[filter,setFilter]=useState("All");const[loading,setLoading]=useState(true);const[error,setError]=useState("");
async function load(){try{if(!getToken()){router.replace("/auth");return}const[c,u]=await Promise.all([api<Course[]>("/courses"),api<{credits_balance:number}>("/auth/me")]);setCourses(c);setBalance(u.credits_balance)}catch(e){setError(e instanceof Error?e.message:"Unable to load courses")}finally{setLoading(false)}}useEffect(()=>{load()},[]);
async function enroll(course:Course){try{await api(`/courses/${course.id}/enroll`,{method:"POST"});router.push("/dashboard")}catch(e){setError(e instanceof Error?e.message:"Unable to enroll")}}
if(loading)return<main className="portal-loading"><img src="/lumi-guide.png" alt="Lumi"/><p>Finding the best paths for you…</p></main>;
const categories=["All",...Array.from(new Set(courses.map(course=>course.category).filter(Boolean)))];const visible=filter==="All"?courses:courses.filter(course=>course.category===filter);
return<main className="portal-shell"><PortalNav/><section className="portal-main"><header className="portal-head"><div><small>EXPLORE LEARNING PATHS</small><h1>Learn foundations. Earn access.</h1><p>Start Python, Java, Web, Data Science, UI/UX, or Game Development free. Use credits earned level by level to unlock specialist paths.</p></div><div className="portal-balance">✦ {balance} credits available</div></header>{error&&<div className="dash-alert">{error}</div>}<div className="course-filters">{categories.map(category=><button className={filter===category?"active":""} key={category} onClick={()=>setFilter(category)}>{category}</button>)}</div><div className="course-grid">{visible.map((course,index)=><article className="surface course-card" key={course.id}><div className="course-cover" style={{background:index%3===1?"linear-gradient(140deg,#0e4c5d,#2c9a91)":index%3===2?"linear-gradient(140deg,#7a3b26,#d17a48)":"linear-gradient(140deg,#271746,#754bd2)"}}><span>{course.credits_required?"🔐":index%2?"⌘":"✦"}</span><small>{course.category??"PERSONALIZED PATH"} • {course.difficulty.toUpperCase()}</small></div><div className="course-body"><div className="access-label">{course.credits_required?`${course.credits_required} CREDIT UNLOCK`:"FREE FOUNDATION"}</div><h2>{course.name}</h2><p>{course.description}</p><small className="course-company">Certificate by {course.certificate_company}</small><div className="course-meta"><span>◷ {course.duration_minutes} min</span><span>⌁ {course.total_levels} levels</span><span>✦ level rewards</span></div><button disabled={!course.enrolled&&!course.can_unlock} onClick={()=>enroll(course)}>{course.enrolled?"Continue roadmap":course.can_unlock?course.credits_required?`Unlock for ${course.credits_required} credits`:"Start free path":`${course.credits_required-balance} more credits needed`}</button></div></article>)}</div><article className="surface feature-strip"><img src="/lumi-guide.png" alt="Lumi"/><div><h2>PathMatch — learning paths that evolve with you</h2><p>Lumi uses your interests, completed skills, quiz mastery, and pace to reorder recommendations after every milestone.</p></div><button>Personalized automatically</button></article></section></main>}
