"use client";
import { useMemo,useState } from "react";import type { TutorAnswer } from "../types";import VisualRenderer from "./VisualRenderer";import VoiceNarrationPlayer from "./VoiceNarrationPlayer";import PracticeQuizPanel from "./PracticeQuizPanel";
type Props={answer:TutorAnswer;onFollowUp:(question:string)=>void;onSave:()=>void};
export default function TutorResponsePanel({answer,onFollowUp,onSave}:Readonly<Props>){
  const tabs=useMemo(()=>[{id:"explanation",label:"Explanation",show:true},{id:"visual",label:"Visual",show:Boolean(answer.visual)},{id:"listen",label:"Listen",show:true},{id:"examples",label:"Examples",show:Boolean(answer.example||answer.code)},{id:"practice",label:"Practice",show:Boolean(answer.quiz)}].filter(tab=>tab.show),[answer]);
  const[active,setActive]=useState(tabs[0].id);const[followUp,setFollowUp]=useState("");const[live,setLive]=useState(false);const narration=[answer.shortAnswer,answer.explanation,...(answer.steps??[]).map(item=>`${item.title}. ${item.narration??item.explanation}`)].join(" ");
  function submit(){if(followUp.trim()){onFollowUp(followUp);setFollowUp("")}}
  return <section className="surface tutor-response" aria-live="polite"><header><div><small>{answer.subject.toUpperCase()} • {answer.difficulty.toUpperCase()}</small><h2>{answer.topic}</h2>{answer.subtopic&&<p>{answer.subtopic}</p>}</div><div className="response-actions"><button onClick={()=>navigator.clipboard?.writeText(narration)}>Copy</button><button onClick={onSave}>Save to Study Hub</button></div></header><nav className="response-tabs" aria-label="Answer sections">{tabs.map(tab=><button className={active===tab.id?"active":""} onClick={()=>setActive(tab.id)} key={tab.id}>{tab.label}</button>)}</nav>
  <div className="response-body">{!answer.safe&&answer.safetyMessage&&<div className="dash-alert" role="alert">{answer.safetyMessage}</div>}
    {active==="explanation"&&<div className="explanation-panel"><h3>{answer.shortAnswer}</h3><p>{answer.explanation}</p>{answer.prerequisites?.length&&<InfoList title="Helpful prerequisites" items={answer.prerequisites}/>} {answer.steps?.map((step,index)=><article className="explanation-step" key={step.id}><span>{index+1}</span><div><b>{step.title}</b><p>{step.explanation}</p></div></article>)}{answer.formula&&<div className="formula-card"><small>FORMULA</small><strong>{answer.formula.expression}</strong><p>{answer.formula.explanation}</p>{answer.formula.variables.map(item=><span key={item.symbol}><b>{item.symbol}</b> {item.meaning}{item.value!==null?` = ${item.value}`:""}</span>)}</div>}{answer.keyPoints&&<InfoList title="Key points" items={answer.keyPoints}/>} {answer.commonMistakes&&<InfoList title="Common mistakes" items={answer.commonMistakes}/>} {answer.realWorldApplications&&<InfoList title="Real-world applications" items={answer.realWorldApplications}/>}</div>}
    {active==="visual"&&answer.visual&&<div className="visual-panel"><div className="visual-title"><div><small>{answer.visual.type.replaceAll("-"," ").toUpperCase()}</small><h3>{answer.visual.title}</h3></div><button onClick={()=>setLive(true)}>Open Live Learning Mode</button></div><VisualRenderer visual={answer.visual}/><p className="section-note">Lumi created the clearest available learning format for this topic.</p></div>}
    {active==="listen"&&<div className="listen-panel"><h3>Listen to Lumi’s explanation</h3><p>No audio starts automatically. Choose Play when you are ready.</p><VoiceNarrationPlayer text={narration}/><details><summary>Narration transcript</summary><p>{narration}</p></details></div>}
    {active==="examples"&&<div>{answer.example&&<article className="example-card"><small>{answer.example.title}</small><h3>{answer.example.problem}</h3>{answer.example.solutionSteps.map((item,index)=><p key={item}><b>{index+1}</b>{item}</p>)}<strong>{answer.example.answer}</strong></article>}{answer.code&&<article className="code-panel"><header><b>{answer.code.language}</b></header><pre>{answer.code.source}</pre><p>{answer.code.explanation}</p>{answer.code.executionSteps.map(item=><span key={`${item.line}-${item.description}`}><b>Line {item.line}</b>{item.description}{item.output&&<em>{item.output}</em>}</span>)}</article>}</div>}
    {active==="practice"&&answer.quiz&&<PracticeQuizPanel quiz={answer.quiz}/>}
  </div><div className="quick-actions">{["Make it simpler","Explain more deeply","Summarize this","Give another example","Explain for an exam"].map(item=><button key={item} onClick={()=>onFollowUp(item)}>{item}</button>)}</div><form className="follow-up-composer" onSubmit={event=>{event.preventDefault();submit()}}><input value={followUp} onChange={event=>setFollowUp(event.target.value)} placeholder="Ask Lumi a follow-up question…" aria-label="Ask a follow-up question"/><button disabled={!followUp.trim()}>Ask →</button></form><div className="generated-followups">{answer.followUpQuestions.map(item=><button onClick={()=>onFollowUp(item)} key={item}>{item}</button>)}</div>
  {live&&answer.visual&&<div className="live-modal" role="dialog" aria-modal="true" aria-label={`Live learning: ${answer.topic}`}><div className="live-workspace"><header><div><small>LIVE LEARNING MODE</small><h2>{answer.topic}</h2></div><button onClick={()=>setLive(false)} aria-label="Exit live learning mode">×</button></header><div className="live-content"><VisualRenderer visual={answer.visual}/><div><img src="/lumi-guide.png" alt="Lumi"/><p>{answer.shortAnswer}</p><VoiceNarrationPlayer text={narration}/><form onSubmit={event=>{event.preventDefault();submit()}}><input value={followUp} onChange={event=>setFollowUp(event.target.value)} placeholder="Ask about this visual…"/><button>Ask Lumi</button></form></div></div></div></div>}
  </section>;
}
function InfoList({title,items}:{title:string;items:string[]}){return <section className="info-list"><h4>{title}</h4><ul>{items.map(item=><li key={item}>{item}</li>)}</ul></section>}
