"use client";
import { FormEvent, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import PortalNav from "../components/PortalNav";
import { api, getToken } from "../lib/api";
import "../portal.css";

type Dashboard={currentCourse:{id:number;name:string}|null};
type Outline={lesson_id:number;lesson_title:string;level_status:string};
type Tools={bookmarked:boolean;note:{content:string}|null;flashcards:Array<{id:string;front:string;back:string}>};
type Plan={id:number;title:string;plan_json:Array<{day:number;title:string;course:string;minutes:number;activities:string[]}>};

export default function StudyTools(){
  const router=useRouter();const[tools,setTools]=useState<Tools|null>(null);const[lesson,setLesson]=useState<Outline|null>(null);const[note,setNote]=useState("");const[plans,setPlans]=useState<Plan[]>([]);const[goal,setGoal]=useState("");const[minutes,setMinutes]=useState(30);const[days,setDays]=useState(7);const[message,setMessage]=useState("");const[loading,setLoading]=useState(true);
  async function load(){try{if(!getToken()){router.replace("/auth");return}const dashboard=await api<Dashboard>("/dashboard");if(!dashboard.currentCourse){setLoading(false);return}const outline=await api<Outline[]>(`/courses/${dashboard.currentCourse.id}/outline`);const next=outline.find(item=>item.level_status!=="locked")??outline[0];if(next){const[data,studyPlans]=await Promise.all([api<Tools>(`/student/lessons/${next.lesson_id}/tools`),api<Plan[]>("/student/study-plans")]);setLesson(next);setTools(data);setNote(data.note?.content??"");setPlans(studyPlans)}}catch(error){setMessage(error instanceof Error?error.message:"Unable to load study tools")}finally{setLoading(false)}}
  useEffect(()=>{load()},[]);
  async function saveNote(){if(!lesson)return;await api(`/student/lessons/${lesson.lesson_id}/note`,{method:"PUT",body:JSON.stringify({content:note})});setMessage("Your lesson note is saved.")}
  async function toggleBookmark(){if(!lesson||!tools)return;const bookmarked=!tools.bookmarked;await api(`/student/lessons/${lesson.lesson_id}/bookmark`,{method:"PUT",body:JSON.stringify({bookmarked})});setTools({...tools,bookmarked});setMessage(bookmarked?"Lesson bookmarked.":"Bookmark removed.")}
  async function generate(event:FormEvent){event.preventDefault();if(!goal.trim())return;const plan=await api<{id:number;title:string;schedule:Plan["plan_json"]}>("/student/study-plans/generate",{method:"POST",body:JSON.stringify({goal,minutesPerDay:minutes,days})});setPlans([{id:plan.id,title:plan.title,plan_json:plan.schedule},...plans]);setMessage("Your AI study plan is ready.");setGoal("")}
  if(loading)return <main className="portal-loading"><img src="/lumi-guide.png" alt="Lumi"/><p>Preparing your study studio…</p></main>;
  return <main className="portal-shell"><PortalNav/><section className="portal-main study-main"><header className="portal-head"><div><small>STUDY SMARTER</small><h1>Your personal study hub.</h1><p>Save thoughts, retain ideas with flashcards, and let Lumi build a daily study plan around your goal.</p></div></header>{message&&<div className="profile-message">{message}</div>}{!lesson?<article className="surface study-empty"><img src="/lumi-guide.png" alt="Lumi"/><h2>Choose a course to unlock your study hub.</h2><button onClick={()=>router.push("/courses")}>Explore courses</button></article>:<><section className="study-grid"><article className="surface study-card"><div className="study-card-head"><div><small>ACTIVE LESSON</small><h2>{lesson.lesson_title}</h2></div><button onClick={toggleBookmark}>{tools?.bookmarked?"★ Bookmarked":"☆ Bookmark"}</button></div><label>Personal notes<textarea value={note} onChange={event=>setNote(event.target.value)} placeholder="Write a summary, question, or insight…"/></label><button className="primary-action" onClick={saveNote}>Save note</button></article><article className="surface study-card"><small>AI FLASHCARDS</small><h2>Recall in small steps.</h2><div className="flashcard-stack">{tools?.flashcards.slice(0,3).map(card=><details key={card.id}><summary>{card.front}<span>Reveal</span></summary><p>{card.back}</p></details>)}</div></article></section><section className="surface plan-builder"><div><small>AI STUDY PLAN</small><h2>Build a plan that fits your time.</h2><p>Lumi distributes focused learning, recall, and practice across your chosen schedule.</p></div><form onSubmit={generate}><input value={goal} onChange={event=>setGoal(event.target.value)} placeholder="e.g. Prepare for Java semester exam" required/><label>Minutes/day<select value={minutes} onChange={event=>setMinutes(Number(event.target.value))}><option value={20}>20 minutes</option><option value={30}>30 minutes</option><option value={45}>45 minutes</option><option value={60}>1 hour</option></select></label><label>Duration<select value={days} onChange={event=>setDays(Number(event.target.value))}><option value={7}>7 days</option><option value={14}>14 days</option><option value={30}>30 days</option></select></label><button className="primary-action">Generate plan</button></form></section><section className="plan-list"><h2>Your plans</h2>{plans.length?plans.map(plan=><article className="surface plan-card" key={plan.id}><h3>{plan.title}</h3><div>{plan.plan_json.slice(0,5).map(day=><p key={day.day}><b>Day {day.day}</b><span>{day.title} · {day.minutes} min</span></p>)}</div></article>):<p className="empty-state">Create your first plan above and Lumi will keep it here.</p>}</section></>}</section></main>;
}
