"use client";
import{useEffect,useMemo,useState}from"react";import{useParams,useRouter}from"next/navigation";import Link from"next/link";import{api,getToken}from"../../lib/api";import"./lesson.css";
type Lesson={id:number;course_id:number;level_id:number;lesson_number:number;title:string;description:string;notes:string;estimated_minutes:number;credits_reward:number;progress_status:string};
type Option={id:number;text:string;isCorrect:number;position:number};type Question={id:number;prompt:string;explanation:string;options:Option[]};type Quiz={id:number;title:string;passing_score:number;questions:Question[]}|null;
type Outline={level_id:number;level_number:number;level_title:string;lesson_id:number;lesson_title:string;estimated_minutes:number;lesson_status:string;level_status:string};
export default function LessonPlayer(){const params=useParams();const router=useRouter();const id=Number(params.lessonId);const[lesson,setLesson]=useState<Lesson|null>(null);const[quiz,setQuiz]=useState<Quiz>(null);const[outline,setOutline]=useState<Outline[]>([]);const[answers,setAnswers]=useState<Record<number,number>>({});const[quizResult,setQuizResult]=useState<{score:number;passed:boolean}|null>(null);const[loading,setLoading]=useState(true);const[finishing,setFinishing]=useState(false);const[seconds,setSeconds]=useState(0);const[focus,setFocus]=useState(false);const[error,setError]=useState("");
useEffect(()=>{if(!focus)return;const timer=window.setInterval(()=>setSeconds(v=>v+1),1000);return()=>clearInterval(timer)},[focus]);
useEffect(()=>{(async()=>{try{if(!getToken()){router.replace("/auth");return}const current=await api<Lesson>(`/lessons/${id}`);setLesson(current);await api(`/lessons/${id}/start`,{method:"POST"});const[q,o]=await Promise.all([api<Quiz>(`/lessons/${id}/quiz`),api<Outline[]>(`/courses/${current.course_id}/outline`)]);setQuiz(q);setOutline(o)}catch(e){setError(e instanceof Error?e.message:"Unable to open lesson")}finally{setLoading(false)}})()},[id,router]);
const concepts=useMemo(()=>lesson?.notes?.split(". ").filter(Boolean).slice(0,4)??[],[lesson]);
async function checkQuiz(){if(!quiz)return;const correct=quiz.questions.filter(q=>q.options.find(o=>o.id===answers[q.id])?.isCorrect).length;const score=Math.round(correct/quiz.questions.length*100);const result=await api<{passed:boolean}>(`/quizzes/${quiz.id}/attempts`,{method:"POST",body:JSON.stringify({score,answers})});setQuizResult({score,passed:result.passed})}
async function finish(){if(!lesson||finishing)return;setFinishing(true);try{const result=await api<{levelCompleted:boolean}>(`/lessons/${lesson.id}/complete`,{method:"POST",body:JSON.stringify({timeSpentSeconds:Math.max(seconds,60)})});router.push(`/dashboard?completed=${result.levelCompleted?"level":"lesson"}`)}catch(e){setError(e instanceof Error?e.message:"Unable to save completion");setFinishing(false)}}
if(loading)return<main className="lesson-loading"><img src="/lumi-guide.png" alt="Lumi"/><p>Opening your lesson…</p></main>;if(!lesson)return<main className="lesson-loading"><h1>Lesson unavailable</h1><p>{error}</p><Link href="/dashboard">Return to roadmap</Link></main>;
const canFinish=!quiz||quizResult?.passed;
return<main className="lesson-shell"><header className="lesson-top"><Link href="/dashboard" className="lesson-brand"><span>L</span>Lumio</Link><div className="lesson-breadcrumb">AI & Machine Learning <b>/</b> Level {Math.floor(lesson.lesson_number/10)}</div><div className="focus-timer"><span>{String(Math.floor(seconds/60)).padStart(2,"0")}:{String(seconds%60).padStart(2,"0")}</span><button onClick={()=>setFocus(v=>!v)}>{focus?"Pause focus":"Start focus"}</button></div></header><div className="lesson-layout">
<aside className="lesson-outline"><small>COURSE JOURNEY</small>{outline.map(item=><button key={item.lesson_id} disabled={item.level_status==="locked"} className={`${item.lesson_id===id?"current":""} ${item.lesson_status==="completed"?"complete":""}`} onClick={()=>router.push(`/learn/${item.lesson_id}`)}><span>{item.lesson_status==="completed"?"✓":item.level_status==="locked"?"🔒":item.level_number}</span><div><b>{item.level_title}</b><em>{item.estimated_minutes} min</em></div></button>)}</aside>
<article className="lesson-content"><div className="lesson-hero"><div><small>LEVEL {Math.floor(lesson.lesson_number/10)} • {lesson.estimated_minutes} MIN</small><h1>{lesson.title}</h1><p>{lesson.description}</p><div className="lesson-reward">✦ Earn {lesson.credits_reward} credits</div></div><img src="/lumi-guide.png" alt="Lumi"/></div>
<section className="learning-section"><small>CORE IDEA</small><h2>Learn it with Lumi</h2><p className="lead">{lesson.notes}</p><div className="concept-grid">{concepts.map((concept,index)=><article key={concept}><span>{["◎","⌁","✦","◇"][index]}</span><div><small>CONCEPT {index+1}</small><p>{concept.replace(/\.$/,"")}.</p></div></article>)}</div></section>
<section className="practice-lab"><div><small>UNIQUE FEATURE • TEACH-BACK LAB</small><h2>Explain it in your own words</h2><p>Imagine you are teaching this idea to a friend. Write a one-sentence explanation. Lumi uses this reflection to strengthen recall.</p></div><textarea placeholder={`I would explain “${lesson.title}” as…`} aria-label="Teach-back reflection"/><div className="coach-note"><img src="/lumi-guide.png" alt="Lumi"/><p><b>Lumi’s coaching cue</b> Use one real-world example and avoid technical words where possible.</p></div></section>
{quiz&&<section className="quiz-section"><small>KNOWLEDGE CHECK</small><h2>{quiz.title}</h2><p>Pass with {quiz.passing_score}% to complete the lesson and unlock roadmap progress.</p>{quiz.questions.map((question,index)=><fieldset key={question.id}><legend>{index+1}. {question.prompt}</legend>{question.options.sort((a,b)=>a.position-b.position).map(option=><label className={quizResult?(option.isCorrect?"correct":answers[question.id]===option.id?"wrong":""):""} key={option.id}><input type="radio" name={`q-${question.id}`} disabled={!!quizResult} checked={answers[question.id]===option.id} onChange={()=>setAnswers(v=>({...v,[question.id]:option.id}))}/><span>{option.text}</span></label>)}{quizResult&&<em>{question.explanation}</em>}</fieldset>)}{quizResult?<div className={`quiz-result ${quizResult.passed?"passed":"retry"}`}><b>{quizResult.passed?"✓ Knowledge check passed":"Keep learning—you’re close"}</b><span>{quizResult.score}%</span>{!quizResult.passed&&<button onClick={()=>{setQuizResult(null);setAnswers({})}}>Try again</button>}</div>:<button className="check-button" disabled={Object.keys(answers).length<quiz.questions.length} onClick={checkQuiz}>Check my answers</button>}</section>}
{error&&<div className="lesson-error">{error}</div>}<footer className="lesson-finish"><div><small>READY TO MOVE FORWARD?</small><b>{canFinish?"Your progress will be saved to MySQL.":"Pass the knowledge check first."}</b></div><button disabled={!canFinish||finishing} onClick={finish}>{finishing?"Saving progress…":"Complete lesson & continue"} <span>→</span></button></footer></article></div></main>}
