"use client";
import{FormEvent,useEffect,useState}from"react";import{useRouter}from"next/navigation";import PortalNav from"../components/PortalNav";import{api,getToken}from"../lib/api";import"../portal.css";
type User={full_name:string;email:string;profile_picture_url?:string;bio?:string;phone_number?:string;country?:string;experience_level:string;credits_balance:number;joined_at:string};
type Interest={id:number;name:string;selected:number};
export default function Profile(){const router=useRouter();const[user,setUser]=useState<User|null>(null);const[interests,setInterests]=useState<Interest[]>([]);const[selected,setSelected]=useState<number[]>([]);const[loading,setLoading]=useState(true);const[saving,setSaving]=useState(false);const[message,setMessage]=useState("");
async function load(){try{if(!getToken()){router.replace("/auth");return}const[u,i]=await Promise.all([api<User>("/auth/me"),api<Interest[]>("/interests")]);setUser(u);setInterests(i);setSelected(i.filter(item=>item.selected).map(item=>item.id))}finally{setLoading(false)}}useEffect(()=>{load()},[]);
async function save(event:FormEvent<HTMLFormElement>){event.preventDefault();setSaving(true);setMessage("");const data=new FormData(event.currentTarget);try{await api("/profile",{method:"PATCH",body:JSON.stringify({fullName:data.get("fullName"),bio:data.get("bio")||null,phoneNumber:data.get("phone")||null,country:data.get("country")||null,profilePictureUrl:data.get("photo")||null,experienceLevel:data.get("experience"),interestIds:selected})});setMessage("Profile and learning preferences saved.");await load()}catch(e){setMessage(e instanceof Error?e.message:"Unable to save profile")}finally{setSaving(false)}}
if(loading||!user)return<main className="portal-loading"><img src="/lumi-guide.png" alt="Lumi"/><p>Opening your profile…</p></main>;
return<main className="portal-shell"><PortalNav/><section className="portal-main"><header className="portal-head"><div><small>YOUR LEARNER IDENTITY</small><h1>Edit your profile.</h1><p>Your interests and experience level directly shape PathMatch recommendations.</p></div><div className="portal-balance">✦ {user.credits_balance} credits</div></header><form className="surface profile-form" onSubmit={save}><div className="profile-summary"><div className="profile-avatar">{user.profile_picture_url?<img src={user.profile_picture_url} alt={user.full_name}/>:user.full_name[0]}</div><div><h2>{user.full_name}</h2><p>{user.email}</p><small>Member since {new Date(user.joined_at).toLocaleDateString()}</small></div></div><div className="profile-fields"><label>Full name<input name="fullName" defaultValue={user.full_name} required/></label><label>Email address<input value={user.email} disabled/></label><label>Phone number<input name="phone" defaultValue={user.phone_number??""} placeholder="+91 98765 43210"/></label><label>Country<input name="country" defaultValue={user.country??""} placeholder="India"/></label><label>Experience level<select name="experience" defaultValue={user.experience_level}><option value="beginner">Beginner</option><option value="intermediate">Intermediate</option><option value="advanced">Advanced</option></select></label><label>Profile picture URL<input name="photo" type="url" defaultValue={user.profile_picture_url??""} placeholder="https://…"/></label><label className="wide">Bio<textarea name="bio" defaultValue={user.bio??""} maxLength={500} placeholder="Tell Lumi about your goals and background."/></label></div><fieldset className="profile-interests"><legend>Learning interests</legend><p>Select any categories you want available in your recommendations.</p><div>{interests.map(item=><button type="button" className={selected.includes(item.id)?"selected":""} key={item.id} onClick={()=>setSelected(current=>current.includes(item.id)?current.filter(id=>id!==item.id):[...current,item.id])}>{item.name}</button>)}</div></fieldset>{message&&<div className="profile-message">{message}</div>}<footer><button disabled={saving}>{saving?"Saving…":"Save profile changes"}</button></footer></form></section></main>}
