import { Router } from "express";
import { z } from "zod";
import { asyncRoute, authenticate } from "../http.js";
import { recordActivity } from "../services/activity.service.js";

const router=Router();
router.use(authenticate);

router.post("/generate",asyncRoute(async(request,response)=>{
  const {prompt,slides}=z.object({prompt:z.string().min(8).max(1000),slides:z.number().int().min(4).max(12).default(7)}).parse(request.body);
  const clean=prompt.replace(/\s+/g," ").trim();
  const topic=clean.replace(/^(create|make|prepare|generate)\s+(a\s+)?(ppt|presentation|slides?)\s+(on|about|for)\s+/i,"");
  const sections=["Why it matters","Core concepts","How it works","Real-world example","Key evidence","Common challenges","Practical application","Summary & next steps"];
  const deck=Array.from({length:slides},(_,index)=>{
    if(index===0)return{title:topic,subtitle:`A personalized presentation generated by Lumio`,bullets:[clean],kind:"title"};
    if(index===slides-1)return{title:"Key takeaways",subtitle:topic,bullets:[`Explain the central idea of ${topic}`,`Connect the topic to a real situation`,"Identify one action or question to explore next"],kind:"summary"};
    const section=sections[(index-1)%sections.length];
    return{title:section,subtitle:topic,bullets:[
      `${section} in the context of ${topic}`,
      `A clear example that makes this idea easier to remember`,
      `One question learners should be able to answer after this slide`,
    ],kind:index%3===0?"visual":"content"};
  });
  await recordActivity(request.user!.id,"ai_chat_usage",`Created presentation: ${topic}`,request.ip,{topic,slides});
  response.json({title:topic,theme:"Lumio violet",slides:deck});
}));

export default router;
