"use client";
import { FormEvent, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import PortalNav from "../components/PortalNav";
import { api,getToken } from "../lib/api";
import "../portal.css";

type Friend={id:number;username:string;full_name:string;profile_picture_url?:string;credits_balance:number;daily_streak:number};
type Request={id:number;username:string;full_name:string;profile_picture_url?:string};
export default function Friends(){
  const router=useRouter();const[friends,setFriends]=useState<Friend[]>([]);const[requests,setRequests]=useState<Request[]>([]);const[query,setQuery]=useState("");const[results,setResults]=useState<Friend[]>([]);const[message,setMessage]=useState("");
  async function load(){try{if(!getToken()){router.replace("/auth");return}const data=await api<{friends:Friend[];requests:Request[]}>("/friends");setFriends(data.friends);setRequests(data.requests)}catch(error){setMessage(error instanceof Error?error.message:"Unable to load friends")}}
  useEffect(()=>{load()},[]);
  async function search(event:FormEvent){event.preventDefault();if(query.trim().length<2)return;try{setResults(await api<Friend[]>(`/friends/search?q=${encodeURIComponent(query)}`))}catch(error){setMessage(error instanceof Error?error.message:"Search failed")}}
  async function add(username:string){try{await api("/friends/requests",{method:"POST",body:JSON.stringify({username})});setMessage(`Friend request sent to @${username}.`);setResults(results.filter(person=>person.username!==username))}catch(error){setMessage(error instanceof Error?error.message:"Unable to send request")}}
  async function respond(id:number,action:"accepted"|"declined"){await api(`/friends/requests/${id}`,{method:"PATCH",body:JSON.stringify({action})});setRequests(requests.filter(item=>item.id!==id));if(action==="accepted")load()}
  return <main className="portal-shell"><PortalNav/><section className="portal-main friends-main"><header className="portal-head"><div><small>LEARN TOGETHER</small><h1>Your learning circle.</h1><p>Connect using usernames, celebrate streaks, and keep one another motivated—just like a study-focused social feed.</p></div><div className="portal-balance">♧ {friends.length} friends</div></header>{message&&<div className="profile-message">{message}</div>}<section className="surface friend-search"><div><small>ADD BY USERNAME</small><h2>Find a friend</h2></div><form onSubmit={search}><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search @username"/><button>Search</button></form>{results.length>0&&<div className="search-results">{results.map(person=><article key={person.id}><span>{person.full_name[0]}</span><div><b>{person.full_name}</b><small>@{person.username}</small></div><button onClick={()=>add(person.username)}>Add</button></article>)}</div>}</section>{requests.length>0&&<section className="request-section"><h2>Friend requests</h2>{requests.map(request=><article className="surface request-card" key={request.id}><span>{request.full_name[0]}</span><div><b>{request.full_name}</b><small>@{request.username} wants to connect</small></div><button onClick={()=>respond(request.id,"accepted")}>Accept</button><button className="quiet" onClick={()=>respond(request.id,"declined")}>Decline</button></article>)}</section>}<section className="friend-list"><h2>Your friends</h2>{friends.length?<div>{friends.map(friend=><article className="surface friend-card" key={friend.id}>{friend.profile_picture_url?<img src={friend.profile_picture_url} alt=""/>:<span>{friend.full_name[0]}</span>}<div><b>{friend.full_name}</b><small>@{friend.username}</small></div><p>🔥 {friend.daily_streak} day streak</p><em>✦ {friend.credits_balance} credits</em></article>)}</div>:<article className="surface study-empty"><img src="/lumi-guide.png" alt="Lumi"/><h2>Your circle starts with one username.</h2><p>Search for a classmate above and send a friend request.</p></article>}</section></section></main>;
}
